services:
  apigateway:
    container_name: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - patientapi
      - identityservice
    networks:
      patientservice_default:
        aliases:
          - apigateway

  frontend:
    container_name: front
    build:
      context: .
      dockerfile: Front/Dockerfile
    ports:
      - "4200:8080"
    networks:
      - patientservice_default

  identityservice:
    container_name: identityservice
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    ports:
      - "5002:8080"
    networks:
      patientservice_default:
        aliases:
          - identityservice

  patientapi:
    container_name: patientapi
    build:
      context: .
      dockerfile: Patient.API/Dockerfile
    ports:
      - "5001:8080"
    networks:
      patientservice_default:
        aliases:
          - patientapi

networks:
  patientservice_default:
    driver: bridge
