services:
  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: apigateway
    ports:
      - "5000:80"
    depends_on:
      - patientapi
      - identityservice

  patientapi:
    build:
      context: .
      dockerfile: Patient.API/Dockerfile
    container_name: patientapi
    ports:
      - "5001:8080"

  identityservice:
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    container_name: identityservice
    ports:
      - "5002:80"
