version: '3.8'
services:
  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:80"


  patientapi:
    build:
      context: .                      # Le contexte = racine de la solution
      dockerfile: Patient.API/Dockerfile
    container_name: patientapi
    ports:
      - "5001:80"

  identityservice:
    build:
      context: .                      # Le contexte = racine de la solution
      dockerfile: IdentityService/Dockerfile
    container_name: identityservice
    ports:
      - "5002:80"
